apiVersion: v1
kind: Pod
metadata:
  name: securityreview-v2
spec:
  securityContext:
    runAsUser: 101
  containers:
  - name:  webguy
    image: antoniantonov/nginx-priviledged:latest
    imagePullPolicy: Always
    containerPort: 8080
    securityContext:
      runAsUser: 101
      allowPrivilegeEscalation: false