apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-mf-job
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: goodnight
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - sleep 30; echo "Hello, son of a gun!"
          restartPolicy: Never
