apiVersion: v1
kind: PersistentVolume
metadata:
  name: reviewvol
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /opt/sfw
    server: k8s-cp   # <-- This needs to match the CP node
    readOnly: false

