apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrole
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secrolebinding
subjects:
- kind: ServiceAccount
  name: securityaccount
  namespace: default
roleRef:
  kind: ClusterRole
  name: secrole
  apiGroup: rbac.authorization.k8s.io