apiVersion: v1
kind: Secret
metadata:
  name: securityaccountsecret
  annotations:
    # The important part is providing this annotation, so the api can generate ca and token.
    kubernetes.io/service-account.name: securityaccount
type: kubernetes.io/service-account-token